project_name: tally

release:
  github:
    owner: choria-io
    name: tally
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

builds:
  - main: main.go
    id: tally
    binary: tally
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

dockers:
  - goos: linux
    goarch: amd64
    skip_push: true
    image_templates:
      - "choria/tally:latest"
      - "choria/tally:{{.Version}}"
    extra_files:
      - README.md
    build_flag_templates:
      - "--platform=linux/amd64"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
