foss:
  compile_targets:
    defaults:
      output: tally-{{version}}-{{os}}-{{arch}}
      strip: true

    64bit_linux:
      os: linux
      arch: amd64

  packages:
    defaults:
      name: tally
      bindir: /usr/sbin
      etcdir: /etc/tally
      release: 1

    el8_64:
      dist: el8
      template: el/el8
      target_arch: x86_64
      binary: 64bit_linux

    el9_64:
      dist: el9
      template: el/el9
      target_arch: x86_64
      binary: 64bit_linux
